# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='term',
            new_name='text',
        ),
        migrations.AddField(
            model_name='article',
            name='file_path',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
