# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0002_auto_20170629_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds_to_monitor', models.IntegerField(default=300)),
                ('tweets_to_get', models.IntegerField(default=15)),
                ('score_threshold', models.FloatField(default=0.6)),
                ('terms_per_article', models.IntegerField(default=5)),
                ('version', models.IntegerField(null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trend.Source')),
            ],
        ),
        migrations.RemoveField(
            model_name='souceparameters',
            name='source',
        ),
        migrations.DeleteModel(
            name='SouceParameters',
        ),
    ]
