# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0004_remove_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='extracted',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='news_url',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='article',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='trend.Article'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='file_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
