# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0005_auto_20170629_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='news_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
